#@ load("@ytt:data", "data")

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: oawofolu/mlflow-server
          imagePullPolicy: Always
          env:
            - name: MLFLOW_S3_ENDPOINT_URL
              value: #@ data.values.artifact_store
            - name: S3_ACCESS_KEY_ID
              value: #@ data.values.access_key
            - name: S3_SECRET_ACCESS_KEY
              value: #@ data.values.secret_key
            - name: MLFLOW_S3_IGNORE_TLS
              value: #@ data.values.ignore_tls
            - name: S3_DEFAULT_REGION
              value: #@ data.values.region
            - name: BACKEND_URI
              value: #@ data.values.backing_store
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: mlflow
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: mlflow-httpproxy
spec:
  routes:
    - conditions:
        - prefix: /
      services:
        - name: mlflow-service
          port: 8080
  virtualhost:
    fqdn: #@ data.values.ingress_fqdn
